apiVersion: v1
kind: Service
metadata:
  name: olivetti-face-recognizer-service
spec:
  type: NodePort
  selector:
    app: olivetti-face-recognizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007